// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FestivalZnanostiApi.Models;

public partial class EventType
{
    public string Type { get; set; }

    public int Id { get; set; }

    public virtual ICollection<Event> Event { get; set; } = new List<Event>();
}