// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace FestivalZnanostiApi.Models;

public partial class FestivalZnanostiContext : DbContext
{
    public FestivalZnanostiContext()
    {
    }

    public FestivalZnanostiContext(DbContextOptions<FestivalZnanostiContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Administrator> Administrator { get; set; }

    public virtual DbSet<Event> Event { get; set; }

    public virtual DbSet<EventType> EventType { get; set; }

    public virtual DbSet<FestivalYear> FestivalYear { get; set; }

    public virtual DbSet<Lecturer> Lecturer { get; set; }

    public virtual DbSet<ParticipantsAge> ParticipantsAge { get; set; }

    public virtual DbSet<Submitter> Submitter { get; set; }

    public virtual DbSet<TimeSlot> TimeSlot { get; set; }

    public virtual DbSet<TimeSlotType> TimeSlotType { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Administrator>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Administ__3214EC075DFC6C7E");

            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.FirstName)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.LastName)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Password)
                .IsRequired()
                .HasMaxLength(1000)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Event>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Event__3214EC0749B4A2E8");

            entity.Property(e => e.Equipment)
                .IsRequired()
                .HasMaxLength(500)
                .IsUnicode(false);
            entity.Property(e => e.Summary)
                .IsRequired()
                .HasMaxLength(500)
                .IsUnicode(false);
            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(200)
                .IsUnicode(false);

            entity.HasOne(d => d.EventType).WithMany(p => p.Event)
                .HasForeignKey(d => d.EventTypeId)
                .HasConstraintName("FK__Event__EventType__30F848ED");

            entity.HasOne(d => d.FestivalYear).WithMany(p => p.Event)
                .HasForeignKey(d => d.FestivalYearId)
                .HasConstraintName("FK__Event__FestivalY__32E0915F");

            entity.HasOne(d => d.Submitter).WithMany(p => p.Event)
                .HasForeignKey(d => d.SubmitterId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK__Event__Submitter__31EC6D26");

            entity.HasMany(d => d.ParticipantsAge).WithMany(p => p.Event)
                .UsingEntity<Dictionary<string, object>>(
                    "ForAge",
                    r => r.HasOne<ParticipantsAge>().WithMany()
                        .HasForeignKey("ParticipantsAgeId")
                        .HasConstraintName("FK__ForAge__Particip__3C69FB99"),
                    l => l.HasOne<Event>().WithMany()
                        .HasForeignKey("EventId")
                        .HasConstraintName("FK__ForAge__EventId__3B75D760"),
                    j =>
                    {
                        j.HasKey("EventId", "ParticipantsAgeId").HasName("PK__ForAge__F266F9B5FCFD33F6");
                    });
        });

        modelBuilder.Entity<EventType>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__EventTyp__3214EC078B7572C2");

            entity.Property(e => e.Type)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
        });

        modelBuilder.Entity<FestivalYear>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Festival__3214EC07411BBD63");

            entity.Property(e => e.Description)
                .IsRequired()
                .HasMaxLength(1000)
                .IsUnicode(false);
            entity.Property(e => e.EndDate).HasColumnType("date");
            entity.Property(e => e.StartDate).HasColumnType("date");
            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(300)
                .IsUnicode(false);
            entity.Property(e => e.Topic)
                .IsRequired()
                .HasMaxLength(300)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Lecturer>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Lecturer__3214EC079113C12A");

            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.FirstName)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.LastName)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Phone)
                .IsRequired()
                .HasMaxLength(15)
                .IsUnicode(false);
            entity.Property(e => e.Resume)
                .HasMaxLength(800)
                .IsUnicode(false);

            entity.HasOne(d => d.Event).WithMany(p => p.Lecturer)
                .HasForeignKey(d => d.EventId)
                .HasConstraintName("FK__Lecturer__EventI__38996AB5");
        });

        modelBuilder.Entity<ParticipantsAge>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Particip__3214EC07B3CDEFF4");

            entity.Property(e => e.Age)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Submitter>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Submitte__3214EC07CCB34D0B");

            entity.HasIndex(e => e.Email, "UQ__Submitte__A9D10534AD7295DA").IsUnique();

            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Password)
                .IsRequired()
                .HasMaxLength(1000)
                .IsUnicode(false);
        });

        modelBuilder.Entity<TimeSlot>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__TimeSlot__3214EC07FE19D3EC");

            entity.Property(e => e.Start).HasColumnType("datetime");

            entity.HasOne(d => d.TimeSlotType).WithMany(p => p.TimeSlot)
                .HasForeignKey(d => d.TimeSlotTypeId)
                .HasConstraintName("FK__TimeSlot__TimeSl__35BCFE0A");

            entity.HasMany(d => d.Event).WithMany(p => p.TimeSlot)
                .UsingEntity<Dictionary<string, object>>(
                    "During",
                    r => r.HasOne<Event>().WithMany()
                        .HasForeignKey("EventId")
                        .HasConstraintName("FK__During__EventId__403A8C7D"),
                    l => l.HasOne<TimeSlot>().WithMany()
                        .HasForeignKey("TimeSlotId")
                        .HasConstraintName("FK__During__TimeSlot__3F466844"),
                    j =>
                    {
                        j.HasKey("TimeSlotId", "EventId").HasName("PK__During__565853B35A03F8D5");
                    });
        });

        modelBuilder.Entity<TimeSlotType>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__TimeSlot__3214EC076222FA70");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}