// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace FestivalZnanostiApi.Models;

public partial class FestivalZnanostiContext : DbContext
{
    public FestivalZnanostiContext()
    {
    }

    public FestivalZnanostiContext(DbContextOptions<FestivalZnanostiContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Account> Account { get; set; }

    public virtual DbSet<Event> Event { get; set; }

    public virtual DbSet<FestivalYear> FestivalYear { get; set; }

    public virtual DbSet<Lecturer> Lecturer { get; set; }

    public virtual DbSet<Location> Location { get; set; }

    public virtual DbSet<ParticipantsAge> ParticipantsAge { get; set; }

    public virtual DbSet<TimeSlot> TimeSlot { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.UseCollation("SQL_Latin1_General_CP1250_CI_AS");

        modelBuilder.Entity<Account>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Account__3214EC075CB9C03D");

            entity.HasIndex(e => e.Email, "UQ__Account__A9D1053494C6B3CE").IsUnique();

            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.FirstName)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.LastName)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Password)
                .IsRequired()
                .IsUnicode(false);
            entity.Property(e => e.Salt)
                .IsRequired()
                .IsUnicode(false);
        });

        modelBuilder.Entity<Event>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Event__3214EC0729176D9B");

            entity.Property(e => e.Equipment)
                .IsRequired()
                .HasMaxLength(500)
                .IsUnicode(false);
            entity.Property(e => e.Summary)
                .IsRequired()
                .HasMaxLength(1800)
                .IsUnicode(false);
            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(200)
                .IsUnicode(false);
            entity.Property(e => e.Type)
                .IsRequired()
                .HasMaxLength(200)
                .IsUnicode(false);

            entity.HasOne(d => d.FestivalYear).WithMany(p => p.Event)
                .HasForeignKey(d => d.FestivalYearId)
                .HasConstraintName("FK__Event__FestivalY__300424B4");

            entity.HasOne(d => d.Location).WithMany(p => p.Event)
                .HasForeignKey(d => d.LocationId)
                .HasConstraintName("FK__Event__LocationI__2E1BDC42");

            entity.HasOne(d => d.Submitter).WithMany(p => p.Event)
                .HasForeignKey(d => d.SubmitterId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK__Event__Submitter__2F10007B");

            entity.HasMany(d => d.ParticipantsAge).WithMany(p => p.Event)
                .UsingEntity<Dictionary<string, object>>(
                    "ForAge",
                    r => r.HasOne<ParticipantsAge>().WithMany()
                        .HasForeignKey("ParticipantsAgeId")
                        .HasConstraintName("FK__ForAge__Particip__3A81B327"),
                    l => l.HasOne<Event>().WithMany()
                        .HasForeignKey("EventId")
                        .HasConstraintName("FK__ForAge__EventId__398D8EEE"),
                    j =>
                    {
                        j.HasKey("EventId", "ParticipantsAgeId").HasName("PK__ForAge__F266F9B537117063");
                    });
        });

        modelBuilder.Entity<FestivalYear>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Festival__3214EC071195CC14");

            entity.Property(e => e.ApplicationStart).HasColumnType("datetime");
            entity.Property(e => e.Description)
                .IsRequired()
                .HasMaxLength(1000)
                .IsUnicode(false);
            entity.Property(e => e.EditUntil).HasColumnType("datetime");
            entity.Property(e => e.EndDate).HasColumnType("datetime");
            entity.Property(e => e.StartDate).HasColumnType("datetime");
            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(300)
                .IsUnicode(false);
            entity.Property(e => e.Topic)
                .IsRequired()
                .HasMaxLength(300)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Lecturer>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Lecturer__3214EC0756894C0C");

            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.FirstName)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.LastName)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Phone)
                .IsRequired()
                .HasMaxLength(15)
                .IsUnicode(false);
            entity.Property(e => e.Resume)
                .HasMaxLength(800)
                .IsUnicode(false);

            entity.HasOne(d => d.Event).WithMany(p => p.Lecturer)
                .HasForeignKey(d => d.EventId)
                .HasConstraintName("FK__Lecturer__EventI__36B12243");
        });

        modelBuilder.Entity<Location>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Location__3214EC07B6C9FF6D");

            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(200)
                .IsUnicode(false);

            entity.HasOne(d => d.ParentLocation).WithMany(p => p.InverseParentLocation)
                .HasForeignKey(d => d.ParentLocationId)
                .HasConstraintName("FK_ParentLocation");
        });

        modelBuilder.Entity<ParticipantsAge>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Particip__3214EC0722546479");

            entity.Property(e => e.Age)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Label)
                .IsRequired()
                .HasMaxLength(2)
                .IsUnicode(false)
                .IsFixedLength();
        });

        modelBuilder.Entity<TimeSlot>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__TimeSlot__3214EC076AE900D7");

            entity.Property(e => e.Start).HasColumnType("datetime");

            entity.HasOne(d => d.FestivalYear).WithMany(p => p.TimeSlot)
                .HasForeignKey(d => d.FestivalYearId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK__TimeSlot__Festiv__33D4B598");

            entity.HasOne(d => d.Location).WithMany(p => p.TimeSlot)
                .HasForeignKey(d => d.LocationId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK__TimeSlot__Locati__32E0915F");

            entity.HasMany(d => d.Event).WithMany(p => p.TimeSlot)
                .UsingEntity<Dictionary<string, object>>(
                    "During",
                    r => r.HasOne<Event>().WithMany()
                        .HasForeignKey("EventId")
                        .HasConstraintName("FK__During__EventId__4316F928"),
                    l => l.HasOne<TimeSlot>().WithMany()
                        .HasForeignKey("TimeSlotId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK__During__TimeSlot__4222D4EF"),
                    j =>
                    {
                        j.HasKey("TimeSlotId", "EventId").HasName("PK__During__565853B33C44020B");
                    });
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}