// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FestivalZnanostiApi.Models;

public partial class FestivalYear
{
    public int Id { get; set; }

    public int Year { get; set; }

    public int Active { get; set; }

    public string Title { get; set; }

    public byte[] Image { get; set; }

    public string Topic { get; set; }

    public string Description { get; set; }

    public DateTime StartDate { get; set; }

    public DateTime EndDate { get; set; }

    public DateTime? EditUntil { get; set; }

    public virtual ICollection<Event> Event { get; set; } = new List<Event>();
}