// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FestivalZnanostiApi.Models;

public partial class Location
{
    public int Id { get; set; }

    public string Name { get; set; }

    public bool TimeSlotsTracked { get; set; }

    public int EventDuration { get; set; }

    public int ParallelEventCount { get; set; }

    public int? ParentLocationId { get; set; }

    public virtual ICollection<Event> Event { get; set; } = new List<Event>();

    public virtual ICollection<Location> InverseParentLocation { get; set; } = new List<Location>();

    public virtual Location ParentLocation { get; set; }

    public virtual ICollection<TimeSlot> TimeSlot { get; set; } = new List<TimeSlot>();
}