// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FestivalZnanostiApi.Models;

public partial class ParticipantsAge
{
    public int Id { get; set; }

    public string Age { get; set; }

    public string Label { get; set; }

    public virtual ICollection<Event> Event { get; set; } = new List<Event>();
}