// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FestivalZnanostiApi.Models;

public partial class Submitter
{
    public int Id { get; set; }

    public string Email { get; set; }

    public string Password { get; set; }

    public int Role { get; set; }

    public string Salt { get; set; }

    public virtual ICollection<Event> Event { get; set; } = new List<Event>();
}