// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FestivalZnanostiApi.Models;

public partial class TimeSlot
{
    public int Id { get; set; }

    public DateTime Start { get; set; }

    public int BookedCount { get; set; }

    public int TimeSlotTypeId { get; set; }

    public virtual TimeSlotType TimeSlotType { get; set; }

    public virtual ICollection<Event> Event { get; set; } = new List<Event>();
}