// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FestivalZnanostiApi.Models;

public partial class TimeSlotType
{
    public int Id { get; set; }

    public int Duration { get; set; }

    public virtual ICollection<TimeSlot> TimeSlot { get; set; } = new List<TimeSlot>();
}